language: java
addons:
  sonarcloud:
    organization: "cfc-kata"
    token:
      secure: "XVtie9jTF1S7Yy0BxTsNBG4JJ8e2n/01EgL44COmvWotmiwB2SIBB02vY2+IjuqNU7ajFVfHmUwfsOnE6muUgk+qyA5CyAA7Wkak5KiTPMlcJZZeOZNI03L5h0XH1Upk3Pp3CqZqzuHMsEVP8hMj2oYGezaywF1FjUTDGB14SUtcmpil8vmCfgyf/ChkZ7wzXT58Mc9QKPG96bqX8cV8IDyH2AOkJHwC5yMAEFUrilZh4/BR4mDm1Zy5fXPKfA3Ht04sl08xU1Jfyd3fHbCDRrg3hgdS6eJ0eK0TCf1nngGOqbhJ3BQA8dHgHz7m+EhmPUxWCPVukfooAverFyq5njBD8X/1q3jGmeFxESdju6KIfUg9cR+2uKiEEjPWab9/GU9/JjAYGZlH3l11QVd0vp/HMdFlHlyZLBjHp1uen0BJWuNzRNq69MC6jxQTyGpgohMPe7SonE6HWfECz9dN+inGmQXzzQO1e2QnqSrSfXcU9S/SjTiCKYkrrlF6szpbxYuYDZrJXsnM8LPpqX1LkJ6TPlesQjio0oo92q/sDfD1pfBDMEZa9yL2Hv+fQynbLBiDocl4mIZrHnbRWlD2xjGb7TOl0TJAkBZbBGNwjTQUwuViyH1q+lNT0vsaCWdBEI0o761GnWPGACRPxqQcmP5WpOPy7I0h5twf+O9x9R0="
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cfc-kata_cfc-kata-loan-team-a
